### ISSUE TITLE
Но ведь функция возвращает bool

### ISSUE THREAD

**Issue by pomponchik** [David2261/RFT_CS#88]
https://github.com/David2261/RFT_CS/blob/956dd5ec3513a3796bfbd08f1885248d6fa08796/tests/rocket_fuel_calculation/test_rocket_fuel_calculation.py#L26

**Comment by pomponchik** [comment]
Ниже полно других функций с той же ошибкой.

**Comment by David2261** [comment]
Исправил типизацию в тестах и проекте
