### ISSUE TITLE
Единицы измерения не указаны

### ISSUE THREAD

**Issue by pomponchik** [David2261/RFT_CS#89]
https://github.com/David2261/RFT_CS/blob/956dd5ec3513a3796bfbd08f1885248d6fa08796/tests/rocket_flight_trajectory/test_rocket_flight_trajectory.py#L21

Код должен в идеале читаться как текст, а тут непонятно, о чем речь.

**Comment by David2261** [comment]
Добавил единицы измерения, но в будущем я хотел добавить функцию выбора ед. изм.. Например, выбор м/с или км/час, чтобы программа было более гибкой и многофункциональной
